### ISSUE TITLE
creating fatJar with gradle is outdated.

### ISSUE THREAD

**Issue by BaigHack3rss** [Col-E/Useful-Things#3]
Hi there,

I wanted to let you guys know that creating a fatJar with gradle page is outdated. the java plugin has been deprecated since gradle 4.10 or (Aug 27 2018) and was removed in gradle 7.0. 
[Source](https://stackoverflow.com/questions/23796404/could-not-find-method-compile-for-arguments-gradle)

I am trying to build a fat jar but turns out that I cannot due to how outdated this part of the repo is.

EDIT: THIS ISSUE IS TOTALY MY FAULT DON'T READ. REVIEW BUILD.GRADLE FILE

**Comment by Col-E** [comment]
> the java plugin has been deprecated since gradle 4.10

It has not. I think you meant to say that the dependency `compile` name scheme has been deprecated. That is not used in this project however. Even so, the included gradle wrapper used is for 7.4 and it runs the `fatJar` task without any deprecation warnings.

Can you elaborate on what issue you are specifically encountering?

**Comment by Col-E** [comment]
Resolution: The issue was the reporter's calling conventions of JavaFX's `Application.launch(...)` on their own project.

The fix is to create a secondary main as in the demo project.
